#!/bin/bash

usage="Help"

while getopts "n:" options; do
  case $options in
    n ) num=$OPTARG;;
    h ) echo $usage;;
    \? ) echo $usage
         exit 1;;
    * ) echo $usage
        exit 1;;
  esac
done

function random_lines {
  count=0
  while read line; do
    lines[$count]=$line
    ((count++))
  done
  line_count=$count

  count=$1
  while [ $count -gt 0 ]; do
    let "number = $RANDOM % $line_count"
    echo ${lines[$number]}
    ((count--))
  done
}

declare -a lines

if [ "$num" = "" ]; then
 num=1
fi

random_lines $num
